schemaVersion: 2.0.0

metadataTest:
  # Image has expected default metadata
  env:
    - key: PORT
      value: 8080
  exposedPorts: [8080]

fileExistenceTests:
  - name: npm
    path: /usr/local/bin/npm
    shouldExist: true
  - name: node
    path: /usr/local/bin/node
    shouldExist: true
  - name: package.json
    path: /home/node/app/package.json
    shouldExist: true

commandTests:
  - name: user is not root
    command: id
    args: ["-u"]
    expectedOutput: ["1000"]
    exitCode: 0
  - name: run node tests
    command: npm
    args: ["run", "test"]
    exitCode: 0