apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "creativesolutions.deploymentname" . }}
  labels:
    {{- include "creativesolutions.appLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "creativesolutions.appSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "creativesolutions.appSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ .Values.serviceaccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            privileged: false
            allowPrivilegeEscalation: false
          {{- if .Values.backend.environments }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
              {{- if eq .Values.backend.service.type "NodePort" }}
                nodePort: {{ .Values.backend.nodePort }}
              {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
