apiVersion: v1
kind: Service
metadata:
  name: {{ include "creativesolutions.servicename" . }}
  labels:
    {{- include "creativesolutions.appLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    {{- include "creativesolutions.appSelectorLabels" . | nindent 4 }}
