schemaVersion: 2.0.0

metadataTest:
  # Image has expected default metadata
  env:
    - key: PORT
      value: 8080
  exposedPorts: [8080]
  # volumes: []
  # entrypoint: []

fileExistenceTests:
  # Main binary exists
  - name: npm
    path: /usr/local/bin/npm
    shouldExist: true
    # permissions: "-rwxr-xr-x"
  - name: node
    path: /usr/local/bin/node
    shouldExist: true
    # permissions: "-rwxr-xr-x"
  - name: package.json
    path: /home/node/app/package.json
    shouldExist: true
    # permissions: "-rwxr-xr-x"

commandTests:
  # Main binary can print its version
  - name: user is not root
    command: id
    args: ["-u"]
    expectedOutput: ["1000"]
    exitCode: 0
  - name: run node tests
    command: npm
    args: ["run", "test"]
    exitCode: 0