version: "3.3"
services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    # volumes:
    #   - mongo_data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081

  web:
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://mongo/chattest
      # - NODE_ENV=production
volumes:
  mongo_data: